baseURL = "https://w1ndyz.github.io/"
languageCode = "zh-cn"
title = "W1ndy's Blog"
hasCJKLanguage = true 
theme = "mogege"

paginate = 11 # 每页的文章数
enableEmoji = true # 支持 Emoji
enableRobotsTXT = true # 支持 robots.txt

preserveTaxonomyNames = true

[Permalinks]
  posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[params]
    author = "w1ndy"                         # Author's name
    avatar = "/images/me/avatar.png"    # Author's avatar
    subtitle = "Something special"                       # Subtitle
    home_mode = ""                      # post or other
    enableGitalk = true                 # gitalk 评论系统

    google_verification = ""

    description = "w1ndy的个人博客" # (Meta) 描述
    keywords = "" # site keywords

    beian = ""
    baiduAnalytics = ""
    googleAnalytics = "" # Google 统计 id

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[markup.goldmark.renderer]
    unsafe = true

[markup.tableOfContents]
    endLevel = 7
    ordered = false
    startLevel = 5